'use client';

export type BudgetStatus =
  | 'Planned'
  | 'Researching'
  | 'Quote Requested'
  | 'Booked'
  | 'Paid'
  | 'Cut';

export type BudgetCategory =
  | 'Venue'
  | 'Planner'
  | 'Catering'
  | 'Entertainment'
  | 'Photography'
  | 'Videography'
  | 'Florals'
  | 'Decor'
  | 'Production'
  | 'Rentals'
  | 'Logistics'
  | 'Beauty'
  | 'Fashion'
  | 'Jewelry'
  | 'Guest Experience'
  | 'Travel'
  | 'Miscellaneous'
  | 'Contingency';

export const CATEGORIES: BudgetCategory[] = [
  'Venue',
  'Planner',
  'Catering',
  'Entertainment',
  'Photography',
  'Videography',
  'Florals',
  'Decor',
  'Production',
  'Rentals',
  'Logistics',
  'Beauty',
  'Fashion',
  'Jewelry',
  'Guest Experience',
  'Travel',
  'Miscellaneous',
  'Contingency',
];

export interface BudgetItem {
  id: string;
  category: BudgetCategory;
  lineItem: string;
  vendor: string;
  status: BudgetStatus;
  estimatedEur: number;
  actualEur: number | null;
  depositPaidEur: number;
  dueDate: string;
  notes: string;
  zone: 'active' | 'considering' | 'cut';
}

export const EUR_USD_RATE = 1.09;
export const GUEST_COUNT = 100;
export const STORAGE_KEY = 'jm-wedding-budget-v3';

export type Scenario = 'Realistic' | 'Luxury' | 'Reduced';
export const SCENARIO_MULTIPLIERS: Record<Scenario, number> = {
  Realistic: 1,
  Luxury: 1.35,
  Reduced: 0.75,
};

export const STATUS_CONFIG: Record<BudgetStatus, { label: string; colors: string }> = {
  Planned:           { label: 'Planned',         colors: 'bg-[#BFCBB2]/30 text-[#5a7a4a]' },
  Researching:       { label: 'Researching',      colors: 'bg-[#C9BFB2]/30 text-[#7a6a5a]' },
  'Quote Requested': { label: 'Quote Requested',  colors: 'bg-[#B7C4CE]/30 text-[#4a6070]' },
  Booked:            { label: 'Booked',           colors: 'bg-[#C9A684]/25 text-[#8a6a44]' },
  Paid:              { label: 'Paid',             colors: 'bg-green-100 text-green-800' },
  Cut:               { label: 'Cut',              colors: 'bg-[#EDE6D8]/60 text-[#C9BFB2]' },
};

export const CATEGORY_COLORS: Record<BudgetCategory, string> = {
  Venue:              '#C9A684',
  Planner:            '#D4C4B8',
  Catering:           '#BFCBB2',
  Entertainment:      '#B7A6C9',
  Photography:        '#D4B896',
  Videography:        '#C8B89A',
  Florals:            '#C4B7A0',
  Decor:              '#B8C9C4',
  Production:         '#A8B8C4',
  Rentals:            '#C9C4B2',
  Logistics:          '#BFC9B8',
  Beauty:             '#E8C4C4',
  Fashion:            '#D4C4D4',
  Jewelry:            '#C9B88A',
  'Guest Experience': '#C4D4B8',
  Travel:             '#B8C4D4',
  Miscellaneous:      '#B8C4B8',
  Contingency:        '#D4B8B8',
};

// All amounts stored in EUR. USD items converted at ÷1.09.
export const DEFAULT_ITEMS: BudgetItem[] = [
  // ── Venue ────────────────────────────────────────────────────────────────────
  {
    id: 'venue-geggiano',
    category: 'Venue',
    lineItem: 'Villa di Geggiano Venue Fee',
    vendor: 'Villa di Geggiano',
    status: 'Booked',
    estimatedEur: 11405,
    actualEur: 11405,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Final payment due 2 weeks before wedding',
    zone: 'active',
  },

  // ── Planner ──────────────────────────────────────────────────────────────────
  {
    id: 'planner-fee',
    category: 'Planner',
    lineItem: 'Wedding Planner Fee',
    vendor: '',
    status: 'Booked',
    estimatedEur: 2288,
    actualEur: 2288,
    depositPaidEur: 0,
    dueDate: '',
    notes: '€2,200 + 4% tax',
    zone: 'active',
  },

  // ── Catering ─────────────────────────────────────────────────────────────────
  {
    id: 'catering-main',
    category: 'Catering',
    lineItem: 'Main Catering (100 guests)',
    vendor: '',
    status: 'Researching',
    estimatedEur: 18000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: '~€180 pp luxury multicourse',
    zone: 'active',
  },
  {
    id: 'catering-indian',
    category: 'Catering',
    lineItem: 'Indian/Kerala Fusion Additions',
    vendor: '',
    status: 'Planned',
    estimatedEur: 4000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Specialty chefs/imported ingredients',
    zone: 'active',
  },
  {
    id: 'catering-bar',
    category: 'Catering',
    lineItem: 'Open Bar',
    vendor: '',
    status: 'Planned',
    estimatedEur: 4500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Premium cocktails/wine',
    zone: 'active',
  },
  {
    id: 'catering-late-night',
    category: 'Catering',
    lineItem: 'Late Night Food Station',
    vendor: '',
    status: 'Planned',
    estimatedEur: 3000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Southern/comfort food or fusion station',
    zone: 'active',
  },
  {
    id: 'catering-cake',
    category: 'Catering',
    lineItem: 'Cake + Desserts',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1200,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Custom cake + desserts',
    zone: 'active',
  },
  {
    id: 'catering-staff-meals',
    category: 'Catering',
    lineItem: 'Staff Meals',
    vendor: '',
    status: 'Planned',
    estimatedEur: 900,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Vendor meals',
    zone: 'active',
  },
  {
    id: 'catering-tableware',
    category: 'Catering',
    lineItem: 'Rentals/Tableware',
    vendor: '',
    status: 'Planned',
    estimatedEur: 2500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Plates, glassware, flatware upgrades',
    zone: 'active',
  },
  {
    id: 'catering-kitchen',
    category: 'Catering',
    lineItem: 'Kitchen/Service Logistics',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Kitchen rentals/staffing',
    zone: 'active',
  },

  // ── Entertainment ─────────────────────────────────────────────────────────────
  {
    id: 'ent-dj-fee',
    category: 'Entertainment',
    lineItem: 'DJ Fee (Mike)',
    vendor: 'Mike DJ',
    status: 'Researching',
    estimatedEur: 7339, // $8,000 ÷ 1.09
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Known quote — $8,000',
    zone: 'active',
  },
  {
    id: 'ent-dj-flights',
    category: 'Entertainment',
    lineItem: 'DJ Flights',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1835, // $2,000 ÷ 1.09
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Estimate for 2 travelers — $2,000',
    zone: 'active',
  },
  {
    id: 'ent-dj-hotel',
    category: 'Entertainment',
    lineItem: 'DJ Hotel/Transport',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1376, // $1,500 ÷ 1.09
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Tuscany lodging/transfers — $1,500',
    zone: 'active',
  },
  {
    id: 'ent-audio',
    category: 'Entertainment',
    lineItem: 'Audio System + Speakers',
    vendor: '',
    status: 'Planned',
    estimatedEur: 3500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Professional outdoor setup',
    zone: 'active',
  },
  {
    id: 'ent-lighting-tech',
    category: 'Entertainment',
    lineItem: 'Lighting Technician',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1200,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Sound/lighting operator',
    zone: 'active',
  },
  {
    id: 'ent-violinist',
    category: 'Entertainment',
    lineItem: 'Violinist',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Ceremony/cocktail hour',
    zone: 'active',
  },
  {
    id: 'ent-saxophone',
    category: 'Entertainment',
    lineItem: 'Saxophone Player',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1200,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Reception/live set',
    zone: 'active',
  },
  {
    id: 'ent-siae',
    category: 'Entertainment',
    lineItem: 'SIAE Music License',
    vendor: '',
    status: 'Planned',
    estimatedEur: 480,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Italian music tax (required)',
    zone: 'active',
  },

  // ── Photography ───────────────────────────────────────────────────────────────
  {
    id: 'photo-package',
    category: 'Photography',
    lineItem: 'Photography Package',
    vendor: '',
    status: 'Researching',
    estimatedEur: 6500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Current quote',
    zone: 'active',
  },
  {
    id: 'photo-albums',
    category: 'Photography',
    lineItem: 'Albums/Prints',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Parent albums/add-ons',
    zone: 'active',
  },

  // ── Videography ───────────────────────────────────────────────────────────────
  {
    id: 'video-package',
    category: 'Videography',
    lineItem: 'Video Package',
    vendor: '',
    status: 'Researching',
    estimatedEur: 8938, // $9,742 ÷ 1.09
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '2026-12-12',
    notes: 'Current estimate — $9,742. Deposits: Dec 12 2026 $3,247 / May 13 2027 $6,495',
    zone: 'active',
  },
  {
    id: 'video-drone',
    category: 'Videography',
    lineItem: 'Drone/Extra Coverage',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Additional edits/drone footage',
    zone: 'active',
  },

  // ── Florals ───────────────────────────────────────────────────────────────────
  {
    id: 'florals-ceremony',
    category: 'Florals',
    lineItem: 'Ceremony Florals',
    vendor: '',
    status: 'Researching',
    estimatedEur: 7320,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'florals-reception',
    category: 'Florals',
    lineItem: 'Reception Florals',
    vendor: '',
    status: 'Researching',
    estimatedEur: 8845,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'florals-bouquet',
    category: 'Florals',
    lineItem: 'Bridal Bouquet + Boutonniere',
    vendor: '',
    status: 'Planned',
    estimatedEur: 305,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'florals-cake',
    category: 'Florals',
    lineItem: 'Cake Flowers',
    vendor: '',
    status: 'Planned',
    estimatedEur: 122,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'florals-petals',
    category: 'Florals',
    lineItem: 'Petals',
    vendor: '',
    status: 'Planned',
    estimatedEur: 165,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'florals-candles',
    category: 'Florals',
    lineItem: 'Candles + Styling',
    vendor: '',
    status: 'Planned',
    estimatedEur: 2500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Luxury tablescape styling',
    zone: 'active',
  },

  // ── Decor ─────────────────────────────────────────────────────────────────────
  {
    id: 'decor-lounge',
    category: 'Decor',
    lineItem: 'Lounge Furniture Rentals',
    vendor: '',
    status: 'Planned',
    estimatedEur: 4000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Cocktail/lounge areas',
    zone: 'active',
  },
  {
    id: 'decor-signage',
    category: 'Decor',
    lineItem: 'Welcome Signage',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1200,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Seating chart, welcome signs',
    zone: 'active',
  },
  {
    id: 'decor-stationery',
    category: 'Decor',
    lineItem: 'Menus/Table Numbers/Stationery',
    vendor: '',
    status: 'Planned',
    estimatedEur: 2500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Luxury print materials',
    zone: 'active',
  },

  // ── Production ────────────────────────────────────────────────────────────────
  {
    id: 'prod-lighting',
    category: 'Production',
    lineItem: 'Bistro/String Lighting',
    vendor: '',
    status: 'Researching',
    estimatedEur: 6100,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'prod-power',
    category: 'Production',
    lineItem: 'Power/Rigging',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Outdoor infrastructure',
    zone: 'active',
  },
  {
    id: 'prod-labor',
    category: 'Production',
    lineItem: 'Labor + Setup Crew',
    vendor: '',
    status: 'Planned',
    estimatedEur: 2000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Install/strike labor',
    zone: 'active',
  },

  // ── Rentals ───────────────────────────────────────────────────────────────────
  {
    id: 'rentals-tables',
    category: 'Rentals',
    lineItem: 'Guest Tables',
    vendor: '',
    status: 'Researching',
    estimatedEur: 660,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'rentals-chairs-reception',
    category: 'Rentals',
    lineItem: 'Reception Chairs',
    vendor: '',
    status: 'Researching',
    estimatedEur: 528,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'rentals-chairs-ceremony',
    category: 'Rentals',
    lineItem: 'Ceremony Chairs',
    vendor: '',
    status: 'Researching',
    estimatedEur: 528,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'rentals-furniture',
    category: 'Rentals',
    lineItem: 'Furniture Rentals',
    vendor: '',
    status: 'Researching',
    estimatedEur: 3660,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },

  // ── Logistics ─────────────────────────────────────────────────────────────────
  {
    id: 'log-delivery',
    category: 'Logistics',
    lineItem: 'Transport/Delivery Fees',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1220,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'log-porters',
    category: 'Logistics',
    lineItem: 'Porters/Handling Crew',
    vendor: '',
    status: 'Planned',
    estimatedEur: 732,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Planner estimate',
    zone: 'active',
  },
  {
    id: 'log-shuttle',
    category: 'Logistics',
    lineItem: 'Guest Shuttle Transportation',
    vendor: '',
    status: 'Planned',
    estimatedEur: 5000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Siena ↔ venue transport',
    zone: 'active',
  },

  // ── Beauty ────────────────────────────────────────────────────────────────────
  {
    id: 'beauty-bride',
    category: 'Beauty',
    lineItem: 'Bridal Hair + Makeup',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Bride only',
    zone: 'active',
  },
  {
    id: 'beauty-party',
    category: 'Beauty',
    lineItem: 'Bridal Party Beauty',
    vendor: '',
    status: 'Planned',
    estimatedEur: 2500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Estimate',
    zone: 'active',
  },

  // ── Fashion ───────────────────────────────────────────────────────────────────
  {
    id: 'fashion-dress',
    category: 'Fashion',
    lineItem: 'Wedding Dress',
    vendor: '',
    status: 'Planned',
    estimatedEur: 8000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Working luxury estimate',
    zone: 'active',
  },
  {
    id: 'fashion-alterations',
    category: 'Fashion',
    lineItem: 'Alterations',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Common hidden cost',
    zone: 'active',
  },
  {
    id: 'fashion-groom',
    category: 'Fashion',
    lineItem: 'Groom Attire',
    vendor: '',
    status: 'Planned',
    estimatedEur: 3000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Tux/shoes/accessories',
    zone: 'active',
  },

  // ── Jewelry ───────────────────────────────────────────────────────────────────
  {
    id: 'jewelry-rings',
    category: 'Jewelry',
    lineItem: 'Wedding Rings',
    vendor: '',
    status: 'Planned',
    estimatedEur: 8000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Estimate',
    zone: 'active',
  },

  // ── Guest Experience ──────────────────────────────────────────────────────────
  {
    id: 'gx-welcome-bags',
    category: 'Guest Experience',
    lineItem: 'Welcome Bags',
    vendor: '',
    status: 'Planned',
    estimatedEur: 3500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Tuscany guest welcome bags',
    zone: 'active',
  },
  {
    id: 'gx-bridesmaid-boxes',
    category: 'Guest Experience',
    lineItem: 'Bridesmaid Proposal Boxes',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1835, // $2,000 ÷ 1.09
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Current luxury direction — $2,000',
    zone: 'active',
  },
  {
    id: 'gx-nanny',
    category: 'Guest Experience',
    lineItem: 'Wedding Nanny',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Estimate',
    zone: 'active',
  },
  {
    id: 'gx-website',
    category: 'Guest Experience',
    lineItem: 'Website + Domain + Tech',
    vendor: '',
    status: 'Planned',
    estimatedEur: 917, // $1,000 ÷ 1.09
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Custom site/tools/email — $1,000',
    zone: 'active',
  },
  {
    id: 'gx-registry',
    category: 'Guest Experience',
    lineItem: 'Registry/Guest Communication',
    vendor: 'WithJoy',
    status: 'Planned',
    estimatedEur: 459, // $500 ÷ 1.09
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'WithJoy/Mailchimp/etc — $500',
    zone: 'active',
  },

  // ── Travel ────────────────────────────────────────────────────────────────────
  {
    id: 'travel-vendor-hotels',
    category: 'Travel',
    lineItem: 'Vendor Hotel Blocks',
    vendor: '',
    status: 'Planned',
    estimatedEur: 4000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Select vendor accommodations',
    zone: 'active',
  },
  {
    id: 'travel-vendor-transport',
    category: 'Travel',
    lineItem: 'Vendor Ground Transport',
    vendor: '',
    status: 'Planned',
    estimatedEur: 2000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Airport + Tuscany transfers',
    zone: 'active',
  },

  // ── Miscellaneous ─────────────────────────────────────────────────────────────
  {
    id: 'misc-legal',
    category: 'Miscellaneous',
    lineItem: 'Legal/Marriage Fees',
    vendor: '',
    status: 'Planned',
    estimatedEur: 1000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Italy paperwork',
    zone: 'active',
  },
  {
    id: 'misc-gratuities',
    category: 'Miscellaneous',
    lineItem: 'Tips/Gratuities',
    vendor: '',
    status: 'Planned',
    estimatedEur: 5000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Vendors/staff',
    zone: 'active',
  },
  {
    id: 'misc-weather',
    category: 'Miscellaneous',
    lineItem: 'Emergency/Weather Backup',
    vendor: '',
    status: 'Planned',
    estimatedEur: 7500,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Tent/rain contingency',
    zone: 'active',
  },
  {
    id: 'misc-fx',
    category: 'Miscellaneous',
    lineItem: 'Currency Conversion Buffer',
    vendor: '',
    status: 'Planned',
    estimatedEur: 3000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'EUR/USD fluctuation',
    zone: 'active',
  },

  // ── Contingency ───────────────────────────────────────────────────────────────
  {
    id: 'contingency',
    category: 'Contingency',
    lineItem: 'General Contingency Reserve',
    vendor: '',
    status: 'Planned',
    estimatedEur: 15000,
    actualEur: null,
    depositPaidEur: 0,
    dueDate: '',
    notes: 'Strongly recommended — ~10% of total',
    zone: 'active',
  },
];

export function eurToUsd(eur: number): number {
  return eur * EUR_USD_RATE;
}

export function fmtUsd(eur: number, multiplier = 1): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(eur * multiplier * EUR_USD_RATE);
}

export function genId(): string {
  return Math.random().toString(36).slice(2, 10);
}
